test_average (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... FAIL
test_to_degrees (__main__.TestExercice) ... FAIL
test_to_farenheit (__main__.TestExercice) ... ok
test_to_radians (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_to_celsius (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 71, in test_to_celsius
    self.assertListEqual(
AssertionError: Lists differ: [-17.77777777777778, -31.666666666666668, 232.7777777777778] != [-17.77777777777778, -31.666666666666664, 232.77777777777777]

First differing element 1:
-31.666666666666668
-31.666666666666664

- [-17.77777777777778, -31.666666666666668, 232.7777777777778]
?                                        ^                  ^

+ [-17.77777777777778, -31.666666666666664, 232.77777777777777]
?                                        ^                  ^^
 : Mauvais calcul de farenheit -> celsius

======================================================================
FAIL: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 59, in test_to_degrees
    self.assertListEqual(
AssertionError: Lists differ: [(114.59155902579234, 6875.49354154754, 412[196 chars]832)] != [(79.0980174562859, 5.881047377154118, 29.6[197 chars]998)]

First differing element 0:
(114.59155902579234, 6875.49354154754, 412529.61249285244)
(79.0980174562859, 5.881047377154118, 29.612494192724625)

- [(114.59155902579234, 6875.49354154754, 412529.61249285244),
-  (-229.18311805158467, -13750.98708309508, -825059.2249857049),
-  (286.47889756448086, 17188.733853868853, 1031324.0312321311),
-  (234.3397382077453, 14060.38429246472, 843623.0575478832)]
+ [(79.0980174562859, 5.881047377154118, 29.612494192724625),
+  (-278.1960349125718, 48.23790524569176, 0.7750116145507491),
+  (257.74504364071475, -15.297381557114704, 44.031235481811564),
+  (213.95544569810457, -2.673258113725865, 23.057550624127998)] : Mauvais calcul de radians -> degres

======================================================================
FAIL: test_to_radians (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 40, in test_to_radians
    self.assertListEqual(
AssertionError: Lists differ: [(-0.08726646259971647, 0.0005817764166666[210 chars]-05)] != [-0.08668468618238503, 0.17598251810595048[32 chars]2748]

First differing element 0:
(-0.08726646259971647, 0.0005817764166666667, 0.0)
-0.08668468618238503

+ [-0.08668468618238503, 0.17598251810595048, 6.283490739798685, 6.9973449482748]
- [(-0.08726646259971647, 0.0005817764166666667, 0.0),
-  (0.17453292519943295, 0.0011635528333333333, 0.0002860400715277778),
-  (6.283185307179586, 0.00029088820833333333, 1.4544410416666669e-05),
-  (6.981317007977318, 0.015998851458333335, 2.9088820833333338e-05)] : Mauvais calcul de degres -> radians

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=3)
